### ISSUE TITLE
Numbers appear like jargon

### ISSUE THREAD

**Issue by impactcolor** [theSage21/handwritten#6]
The script works great but when ti comes to numbers they appear like scribbles.  Is there a work around to include numbers?

**Comment by theSage21** [comment]
Not really. Since this script is using a pre trained model hosted on Graves' site we cannot change anything that they don't allow via the API.

If you really need this, I'd recommend retraining the model. The code is available on github in [rnnlib](https://github.com/szcom/rnnlib). Again, your results will be almost the same if you don't make changes to the dataset / training method.
